version: 1.0.{build}
skip_branch_with_pr: true
image: Visual Studio 2019
build:
  parallel: true
build_script:
- cmd: >-
    git clone --depth=1 --branch=unit-testing https://github.com/ModOrganizer2/modorganizer-umbrella.git c:\projects\modorganizer-umbrella 2> $null

    mkdir c:\projects\modorganizer-build -type directory

    cd c:\projects\modorganizer-umbrella

    C:\Python37-x64\python.exe unimake.py -d c:\projects\modorganizer-build -s Appveyor_Build=True %APPVEYOR_PROJECT_NAME%
artifacts:
- path: build\bsa_packer.dll
  name: bsa_packer_dll
- path: build\bsa_packer.pdb
  name: bsa_packer_pdb
- path: build\bsa_packer.lib
  name: bsa_packer_lib
