name: C/C++ CI

on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ actions-test ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.6.2
        with:
          # Version of Qt to install
          version: 5.14.2
          # Whether or not to install Qt dependencies on Linux
          install-deps: false
          # Additional Qt modules to install
          # modules: # optional
      - name: run-cmake
        uses: lukka/run-cmake@v2.5
        with:
          # Select the build configuration, typically Debug or Release. Used by CMakeListsTxtBasic mode.
          cmakeBuildType: RelWithDebInfo
          # Specify the CMake generator to use. Possible values: Ninja: Ninja, NinjaMulti: Ninja Multi-Config UnixMakefiles: Unix Makefiles, VS16Win64: Visual Studio 2019 x64, VS16Arm64: Visual Studio 2019 ARM64, VS16Arm: Visual Studio 2019 ARM, VS16Win32: Visual Studio 2019 Win32, VS15Win64: Visual Studio 2017 x64, VS15Arm64: Visual Studio 2017 ARM64, VS15Arm: Visual Studio 2017 ARM, VS15Win32: Visual Studio 2017 Win32. Used by CMakeListsTxtBasic mode.
          cmakeGenerator: VS16Win64
